# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: testing with jest

on:
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - ".storybook/**"
      - "public/**"
    branches-ignore:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          scope: "@datasigninc"
          cache: yarn

      - name: Install libraries
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: run test suite
        run: yarn test
